stages:
  # trigger child pipelines for different sub-projects
 - trigger

# trigger the pipeline for the flask project
trigger_flask_pipeline:
  stage: trigger
  trigger:
    include: .gitlab-ci/flask.gitlab-ci.yml

# trigger the pipeline for the react project
trigger_react_pipeline:
  stage: trigger
  trigger:
    include: .gitlab-ci/react.gitlab-ci.yml